// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCode.Templates
{
    using System.Xml.Serialization;
    using System.IO;
    using System.Collections.Generic;
    using DataSource;
    using System;
    
    
    #line 1 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class Solution : SolutionBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            
            #line 9 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"

var tmp = new XmlSerializer(typeof(Software))
                             .Deserialize(
                                 new FileStream("Last.xml",
                                                FileMode.Open,
                                                FileAccess.ReadWrite,
                                                FileShare.ReadWrite)) as Software;

            
            #line default
            #line hidden
            this.Write("\r\nMicrosoft Visual Studio Solution File, Format Version 11.00\r\n# Visual Studio 20" +
                    "10\r\nProject(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"");
            
            #line 20 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.DALNameSpace));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 20 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.DALNameSpace));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 20 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.DALNameSpace));
            
            #line default
            #line hidden
            this.Write(".csproj\", \"{F95BD633-8D10-4891-8464-1D9E91ACF676}\"\r\nEndProject\r\nProject(\"{FAE04EC" +
                    "0-301F-11D3-BF4B-00C04F79EFBC}\") = \"");
            
            #line 22 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.ModelNameSpace));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 22 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.ModelNameSpace));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 22 "E:\桌面\WorkSpace\AutoCode\AutoCode\Templates\Solution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.ModelNameSpace));
            
            #line default
            #line hidden
            this.Write(".csproj\", \"{53D5F634-CCB4-49EF-89CB-54F0B4787D12}\"\r\nEndProject\r\nGlobal\r\n    Globa" +
                    "lSection(SolutionConfigurationPlatforms) = preSolution\r\n        Debug|Any CPU = " +
                    "Debug|Any CPU\r\n        Debug|Mixed Platforms = Debug|Mixed Platforms\r\n        De" +
                    "bug|x86 = Debug|x86\r\n        Release|Any CPU = Release|Any CPU\r\n        Release|" +
                    "Mixed Platforms = Release|Mixed Platforms\r\n        Release|x86 = Release|x86\r\n  " +
                    "  EndGlobalSection\r\n    GlobalSection(ProjectConfigurationPlatforms) = postSolut" +
                    "ion\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676}.Debug|Any CPU.ActiveCfg = De" +
                    "bug|Any CPU\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676}.Debug|Any CPU.Build." +
                    "0 = Debug|Any CPU\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676}.Debug|Mixed Pl" +
                    "atforms.ActiveCfg = Debug|Any CPU\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676" +
                    "}.Debug|Mixed Platforms.Build.0 = Debug|Any CPU\r\n        {F95BD633-8D10-4891-846" +
                    "4-1D9E91ACF676}.Debug|x86.ActiveCfg = Debug|Any CPU\r\n        {F95BD633-8D10-4891" +
                    "-8464-1D9E91ACF676}.Release|Any CPU.ActiveCfg = Release|Any CPU\r\n        {F95BD6" +
                    "33-8D10-4891-8464-1D9E91ACF676}.Release|Any CPU.Build.0 = Release|Any CPU\r\n     " +
                    "   {F95BD633-8D10-4891-8464-1D9E91ACF676}.Release|Mixed Platforms.ActiveCfg = Re" +
                    "lease|Any CPU\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676}.Release|Mixed Plat" +
                    "forms.Build.0 = Release|Any CPU\r\n        {F95BD633-8D10-4891-8464-1D9E91ACF676}." +
                    "Release|x86.ActiveCfg = Release|Any CPU\r\n        {53D5F634-CCB4-49EF-89CB-54F0B4" +
                    "787D12}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n        {53D5F634-CCB4-49EF-89C" +
                    "B-54F0B4787D12}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n        {53D5F634-CCB4-49" +
                    "EF-89CB-54F0B4787D12}.Debug|Mixed Platforms.ActiveCfg = Debug|Any CPU\r\n        {" +
                    "53D5F634-CCB4-49EF-89CB-54F0B4787D12}.Debug|Mixed Platforms.Build.0 = Debug|Any " +
                    "CPU\r\n        {53D5F634-CCB4-49EF-89CB-54F0B4787D12}.Debug|x86.ActiveCfg = Debug|" +
                    "Any CPU\r\n        {53D5F634-CCB4-49EF-89CB-54F0B4787D12}.Release|Any CPU.ActiveCf" +
                    "g = Release|Any CPU\r\n        {53D5F634-CCB4-49EF-89CB-54F0B4787D12}.Release|Any " +
                    "CPU.Build.0 = Release|Any CPU\r\n        {53D5F634-CCB4-49EF-89CB-54F0B4787D12}.Re" +
                    "lease|Mixed Platforms.ActiveCfg = Release|Any CPU\r\n        {53D5F634-CCB4-49EF-8" +
                    "9CB-54F0B4787D12}.Release|Mixed Platforms.Build.0 = Release|Any CPU\r\n        {53" +
                    "D5F634-CCB4-49EF-89CB-54F0B4787D12}.Release|x86.ActiveCfg = Release|Any CPU\r\n   " +
                    " EndGlobalSection\r\n    GlobalSection(SolutionProperties) = preSolution\r\n        " +
                    "HideSolutionNode = FALSE\r\n    EndGlobalSection\r\nEndGlobal\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class SolutionBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
