// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCode.Templates
{
    using System.Xml.Serialization;
    using System.IO;
    using System.Collections.Generic;
    using DataSource;
    using System;
    
    
    #line 1 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class DALModelList : DALModelListBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            
            #line 9 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"

var tmp = new XmlSerializer(typeof(Software))
                             .Deserialize(
                                 new FileStream("Last.xml",
                                                FileMode.Open,
                                                FileAccess.ReadWrite,
                                                FileShare.ReadWrite)) as Software;
foreach (var database in tmp.Databases)
{
    var name = "DataSourceRepository." + database.Name + "DataSource";
    var dataSource = name + ".DataSource";
    foreach (var table in database.Tables)
    {
            
            #line default
            #line hidden
            this.Write("using System.Collections.Generic;\r\nusing System.Data.SQLite;\r\nusing System.Linq;\r" +
                    "\nusing ");
            
            #line 25 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.DALNameSpace));
            
            #line default
            #line hidden
            this.Write(".Services.");
            
            #line 25 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(database.Name));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 26 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.ModelNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 26 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(database.Name));
            
            #line default
            #line hidden
            this.Write(";\r\nusing System;\r\n\r\nnamespace ");
            
            #line 29 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tmp.DALNameSpace));
            
            #line default
            #line hidden
            this.Write(".Models.");
            
            #line 29 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(database.Name));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class DAL");
            
            #line 31 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public List<Model");
            
            #line 33 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("> Lists { get; set; }\r\n        internal List<Model");
            
            #line 34 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("> cache;\r\n\r\n\t\t/// <summary>\r\n        /// 生成count=0的列表，已存入缓存。没有数据库操作。\r\n        ///" +
                    " </summary>\r\n        public DAL");
            
            #line 39 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            Lists = new List<Model");
            
            #line 41 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n            cache = new List<Model");
            
            #line 42 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n        }\r\n\t\t/// <summary>\r\n        /// 按条件查询列表，未存入缓存。有数据库操作。\r\n        /// " +
                    "</summary>\r\n        /// <param name=\"strWhere\">条件：不要包括“where”，当为null或string.Empt" +
                    "y时为无条件查询。</param>\r\n        /// <exception cref=\"SQLiteException\"></exception>\r\n\t" +
                    "\tpublic DAL");
            
            #line 49 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("(string strWhere)\r\n        {\r\n            Lists = DAL");
            
            #line 51 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(@"Service.GetModelList(strWhere);
        }
		/// <summary>
        /// 按条件查询分页列表，未存入缓存。有数据库操作。
        /// </summary>
        /// <param name=""strWhere"">条件：不要包括“where”，当为null或string.Empty时为无条件查询。</param>
        /// <param name=""strOrderby"">排序字段，不要包括“order by”,当为null或string.empty是为默认排序</param>
        /// <param name=""limit"">所取的记录数</param>
        /// <param name=""offset"">跳过的记录数</param>
        /// <exception cref=""SQLiteException""></exception>
        /// <exception cref=""ArgumentException""></exception>
        public DAL");
            
            #line 62 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(@"(string strWhere, string strOrderby, int limit, int offset)
        {
            if (limit < 0)
            {
                throw new ArgumentException(""Is Negative."", ""limit"");
            }
            if (offset < 0)
            {
                throw new ArgumentException(""Is Negative."", ""offset"");
            }
            Lists = DAL");
            
            #line 72 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(@"Service.GetModelList(strWhere, strOrderby, limit, offset);
        }
        /// <exception cref=""ArgumentException""></exception>
        public void SaveToCache()
        {
            if (Lists == null)
            {
                throw new ArgumentException(""Lists is Null."");
            }
            cache = Lists.Select(l => l.Clone()).ToList();
        }
        /// <exception cref=""SQLiteException""></exception>
        /// <exception cref=""ArgumentException""></exception>
        public void SaveChanges()
        {
            if (Lists == null || cache == null)
            {
                throw new ArgumentException(""Lists and cache is Null."");
            }
            DAL");
            
            #line 91 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(@"Service.SaveChanges(cache, Lists);
        }
        /// <exception cref=""ArgumentException""></exception>
        public void DropChanges()
        {
            if (cache == null)
            {
                throw new ArgumentException(""cache is Null."");
            }
            Lists = cache.Select(l => l.Clone()).ToList();
        }
    }
}DALModelListRemark20130515");
            
            #line 103 "E:\SVN\AutoCode2\trunk\AutoCode\Templates\DALModelList.tt"
}
}
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class DALModelListBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
